# Generated by Django 4.1.2 on 2023-04-17 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(max_length=200)),
                ('Course_Code', models.CharField(max_length=30)),
                ('Course_Duration', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ExamOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Registration_Number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Faculty_Name', models.CharField(max_length=200)),
                ('Faculty_Coordinator', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Code', models.CharField(max_length=10)),
                ('Course_Name', models.CharField(max_length=150)),
                ('Year_Of_Exam', models.CharField(choices=[('1', 'Year 1'), ('2', 'Year 2'), ('3', 'Year 3'), ('4', 'Year 4'), ('5', 'Year 5')], max_length=20)),
                ('Academic_session', models.CharField(choices=[('semester', 'Semester'), ('quarter', 'Quarter')], max_length=50)),
                ('Semester_l_Quarter', models.CharField(choices=[('S1', 'Semester 1'), ('S2', 'Semester 2'), ('S3', 'Semester 3'), ('S4', 'Semester 4'), ('S5', 'Semester 5'), ('S6', 'Semester 6')], max_length=20)),
                ('Session', models.CharField(choices=[('DAY', 'Day'), ('EVENING', 'Evening'), ('WEEKEND', 'Weekend')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Registration_number', models.CharField(max_length=20)),
                ('Current_Year', models.CharField(choices=[('1', 'Year 1'), ('2', 'Year 2'), ('3', 'Year 3'), ('4', 'Year 4'), ('5', 'Year 5'), ('6', 'Year 6')], max_length=20)),
                ('Email', models.EmailField(max_length=100)),
                ('Phone_Number', models.CharField(max_length=20)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.course')),
                ('Faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.faculty')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='Faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.faculty'),
        ),
    ]
