# Generated by Django 4.1.2 on 2023-05-15 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
       
        migrations.RemoveField(
            model_name='sessionlist',
            name='Study',
        ),
        migrations.AddField(
            model_name='sessionlist',
            name='Study_mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.studysession'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='Study_mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.studysession'),
        ),
    ]
