# Generated by Django 4.1.2 on 2023-04-28 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_studysession_alter_student_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionlist',
            old_name='Session_name',
            new_name='Session',
        ),
    ]
