# Generated by Django 4.1.2 on 2023-07-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_remove_accounts_results_copy_accounts_complaint_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='User_passcode',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
