# Generated by Django 4.1.2 on 2023-05-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_complaint_lecturer_complaint_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='AR_approval',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='Accounts_approval',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='Attachment',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='Exam_office_approval',
            field=models.BooleanField(),
        ),
    ]
