# Generated by Django 4.1.2 on 2023-05-02 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_rename_session_name_sessionlist_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remark',
            old_name='Semester_l_Quarter',
            new_name='SemesterQuarter',
        ),
    ]
