# Generated by Django 4.1.2 on 2023-05-02 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_rename_course_code_remark_paper_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Course_Code',
        ),
    ]
