# Generated by Django 4.1.2 on 2023-07-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_alter_results_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='is_store_approved',
            field=models.CharField(choices=[('Not Found', 'Not Found'), ('Retrieved', 'Retrieved')], max_length=30),
        ),
    ]
