# Generated by Django 4.1.2 on 2023-07-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_alter_complaint_is_store_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='Assigned_Lecturer',
            field=models.CharField(default='', max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='Complaint_resolved',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Approved', 'Complaint Resolved')], default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='to_ar',
            field=models.CharField(choices=[('ar', 'Send to Academic Registrar')], default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accounts',
            name='Complaint_type',
            field=models.CharField(default='Remark', max_length=10),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='is_exam_office_approved',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Approved', 'Complaint Resolved')], max_length=30),
        ),
        migrations.AlterField(
            model_name='results',
            name='Sem_Qter',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=30),
        ),
    ]
