# Generated by Django 4.1.2 on 2023-05-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_lecturer_ar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Registration_number', models.CharField(max_length=15)),
                ('Phone_number', models.CharField(max_length=15)),
                ('Reason', models.CharField(max_length=15)),
            ],
        ),
    ]
